# Path save and load model
result_dir: "result" #Directory to store results
save_dir: "" #Save image training to train.txt and test.txt
image_dir: "G:/PYTHON/special_characters" #Directory to image training
ckp_freq: 1 #Checkpoint Frequency (default: 1)
ckp: "" #path to load checkpoint
exp_name: "exp" #name of experiment

# dataset and num class
test_size: 0.2 #Test size default: 20%
image_size: (224, 224) #Image size default: (224,224)
num_class: 2
batch_size: 32

#device
cuda: True #enables CUDA training

#training
epochs: 50
lr: 0.0001
train_log_step: 100 #

